image: 3.7-alpine

before_script:
  - pip install poetry
  - poetry install 

stages:
  - code-quality
  - test
  #- test-build
  #- deploy

pylint:
  stage: code-quality
  script:
    - make pylint

black:
  stage: code-quality
  script:
    - black --check src

pydocstyle:
  stage: code-quality
  allow_failure: true
  script:
    - make pydocstyle

test:
  stage: test
  script:
    - make test
  artifacts:
    paths:
      -htmlcov
    expire_in: 30 days

mypy:
  stage: test
  script:
    - make mypy
