# https://docs.gitlab.com/ee/user/packages/container_registry/

image: docker:19.03.12
services:
  - docker:19.03.12-dind


stages:
 - container-build
 - code-quality
 - test
 #- test-build
 - deploy

pages:
  stage: deploy
  script:
    - echo "Copying public dic..."
  artifacts:
    paths:
      - public
  only:
    - main

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest


container-build:
  stage: container-build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    changes:
      - Dockerfile
      - poetry.lock
      - pyproject.toml
      - .gitlab-ci.yml


# --- code-quality ----------------------------------------------- 
 
pylint:
 extends: .test_template 
 stage: code-quality
 allow_failure: true
 script:
  - docker run -v $(pwd):/code/:ro $CONTAINER_TEST_IMAGE make pylint

black:
 extends: .test_template 
 stage: code-quality
 script:
  - docker run -v $(pwd):/code/:ro $CONTAINER_TEST_IMAGE poetry run black --check .

pydocstyle:
 extends: .test_template 
 stage: code-quality
 allow_failure: true
 script:
  - docker run -v $(pwd):/code/:ro $CONTAINER_TEST_IMAGE make pydocstyle


# --- tests ----------------------------------------------- 

#https://stackoverflow.com/questions/54074433/gitlab-ci-specifying-stages-in-before-script
.test_template:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY    
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
  stage: test

pytest:
 extends: .test_template 
 script:
  - docker run -v $(pwd):/code/ $CONTAINER_TEST_IMAGE make test
 artifacts:
  paths:
   - htmlcov
  expire_in: 30 days

mypy:
 extends: .test_template 
 script:
  - docker run -v $(pwd):/code/:ro $CONTAINER_TEST_IMAGE make mypy
