stages:
  - code-quality
  - test
  #- test-build
  #- deploy

pylint:
  image: lasnq/openqlab
  stage: code-quality
  script:
    - make pylint

black:
  image: lasnq/openqlab
  stage: code-quality
  script:
    - black --check src

pydocstyle:
  image: lasnq/openqlab
  stage: code-quality
  allow_failure: true
  script:
    - make pydocstyle

test:
  image: 3.7-alpine
  stage: test
  script:
    - make test
  artifacts:
    paths:
      -htmlcov
    expire_in: 30 days

mypy:
