default:
 image: lasnq/$CI_PROJECT_NAME:latest

stages:
 - container-build
 - code-quality
 - test
 #- test-build
 #- deploy

container-build:
 stage: container-build
 script:
  - podman login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY_HOST
  - podman build -t $CI_PROJECT_NAME .
  - podman tag $CI_PROJECT_NAME lasnq/$CI_PROJECT_NAME:latest
  - podman push lasnq/$CI_PROJECT_NAME:latest
 tags:
  - container-builder  
 only:
  changes:
   - Dockerfile
   - poetry.lock
   - pyproject.toml
   #- .gitlab-ci.yml

 
pylint:
 stage: code-quality
 allow_failure: true
 script:
  - make pylint

black:
 stage: code-quality
 script:
  - poetry run black --check .

pydocstyle:
 stage: code-quality
 allow_failure: true
 script:
  - make pydocstyle

test:
 stage: test
 script:
  - make test
 artifacts:
  paths:
   - htmlcov
  expire_in: 30 days

mypy:
 stage: test
 script:
  - make mypy
