default:
 image: python:3.7
 before_script:
  - pip --no-cache-dir install poetry
  - poetry install

stages:
 - container-build
 - code-quality
 - test
 #- test-build
 #- deploy

container-build:
 stage: container-build
 before_script: []
 script:
  #- echo "Hello Build"
  - podman build .
 tags:
  - container-builder  

 
pylint:
 stage: code-quality
 allow_failure: true
 script:
  - make pylint

black:
 stage: code-quality
 script:
  - make black

pydocstyle:
 stage: code-quality
 allow_failure: true
 script:
  - make pydocstyle

test:
 stage: test
 script:
  - make test
 artifacts:
  paths:
   - htmlcov
  expire_in: 30 days

mypy:
 stage: test
 script:
  - make mypy
