default:
 image: python:3.7
 before_script:
  - pip --no-cache-dir install poetry
  - poetry install

stages:
 - docker-build
 - code-quality
 - test
 #- test-build
 #- deploy

docker-build:
 image: docker:stable
 stage: docker-build
 script:
  - echo "Hello Build"
 tags:
  - docker-build  

 
pylint:
 stage: code-quality
 script:
  - make pylint

black:
  stage: code-quality
  script:
    - black --check src

pydocstyle:
  stage: code-quality
  allow_failure: true
  script:
    - make pydocstyle

test:
  stage: test
  script:
    - make test
  artifacts:
    paths:
      - htmlcov
    expire_in: 30 days

mypy:
  stage: test
  script:
    - make mypy
