# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: \.csv$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

repos:
  - repo: local
    hooks:
      - id: seed-isort-config
        name: seed-isort-config
        stages: [commit]
        language: system
        entry: pipenv run seed-isort-config
        pass_filenames: false
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
